Update readme.md
IntroToCode/CodeMates1_Fall22 pull request #18
Opened 2022-10-26 18:57 UTC by uiseokh

## 🎯 Objective

Completing the recipe

## 🛠️ Changes made

Changed the direction of items based on what Julian wrote

## 👥 Who needs to review this Pull Request? 

@Minjee7377 @edsonfdl

2022-10-26 19:32 UTC, edsonfdl requested changes
Hi Jason, I would change "garlic" to "minced garlic", otherwise looks fine :)

2022-10-26 19:38 UTC, Minjee7377 approved these changes

2022-10-26 19:40 UTC, Minjee7377 approved these changes

2022-10-26 19:44 UTC, Minjee7377 approved these changes

2022-10-26 19:44 UTC, Minjee7377 approved these changes

2022-10-26 22:34 UTC, hdzhu1265 approved these changes

2022-10-27 00:50 UTC, edsonfdl approved these changes
Awesome thanks!

2022-10-27 00:55 UTC, merged

2022-10-27 00:55 UTC, edsonfdl commented
Confirming merge after having the 3 approvals